### PR TITLE
Bug 1164316 - add 'effects' icon into gaia-icons.

### PR DESCRIPTION
**Pull request by mpizza**

### CODE REVIEW

**Comment by wilsonpage** [comment]
It doesn't look like the font files changed. Did you run `$ grunt`?

**Comment by mpizza** [comment]
Yes, I did it, and see the screen shot as  above.

**Comment by wilsonpage** [comment]
screenshot 2015-05-13 11 50 47

Perhaps you didn't add the files to the commit?

**Comment by mpizza** [comment]
Oh~~~ I made a stupid mistake, so sorry. I've attached `gaia-icons.ttf` please help to review it again.
Thanks.

**Comment by wilsonpage** [comment]
STAMPED https://github.com/gaia-components/gaia-icons/releases/tag/v0.8.0

**Pull request merged**
